### ISSUE TITLE
[BUG] 1.1.3 crashes browser immediately

### ISSUE THREAD

**Issue by Mystqr4** [ACK-J/Port_Authority#31]
**Describe the bug**
As soon as I got this update my browser crashed/forced close. It had been fine for days. I reopened Waterfox and again within a few seconds of the browser opening it would disappear. 
I then ran Waterfox in safe mode and looked at my most recent updates and figured straight away that it was this extension and proceeded to disabled it and restarted my browser as normal and now without it enabled everything is running rock solid again.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Waterfox G5.19
 - Version Port Authority 1.1.3

**Comment by ACK-J** [comment]
Installing waterfox now to see why that happens.

**Comment by ACK-J** [comment]
Can you provide any other debugging information. I am not able to reproduce this. I installed the extension without a crash and then I had it update from 1.1.2 to 1.1.3 without any issue

**Comment by ACK-J** [comment]
I have just released v1.1.4 which reverts changes back to v1.1.2 as there seems to be a lot of issues. Please let me know if that fixes your issue for the time being and if you have any other debugging information.

**Comment by Mystqr4** [comment]
Sorry for the slow reply. Here is a list of the extensions I am running. There is a fair bit of redundancy that I need to sort out but overall this is generally what I am running. I will update to the latest version of the rolled back code and report back when I can.
Thank you.

'Improve YouTube!' 🎧 (for YouTube & Videos) 4.27 (Updated at same time)
Absolute Enable Right Click & Copy 1.3.8
AutoAuth 3.1.1
Behind The Overlay 0.2.1
Bypass Paywalls Clean 3.2.7.0 (Updated at same time)
CanvasBlocker 1.9
ClearURLs 1.26.1
Consent-O-Matic 1.0.12
ContextSearch web-ext 1.46.14
Copy PlainText 1.15
Demodal - Block modals and overlays 1.0.4
Don't Accept image/webp 0.8.2
Element Blocker 2.1
FastForward 0.2237
Forget Me Not - Forget cookies & other data 2.2.8
Form History Control (II) 2.5.6.1
Free Download Manager 3.0.57
Grabby 0.62.15
I still don't care about cookies 1.1.1
IDM Integration Module 6.41.12
Image saver 1.0.1
image-resizer 1.7.2c
Imagus mod 0.10.14.7
Link Gopher 2.4.4
Minimal Theme for Twitter 5.1.4
MyJDownloader Browser Extension 3.3.20
Overlay Remover Auto 1.1
Popup This Video 1.3.0
Popup Video(WebExtension) 0.0.10
Popup window 0.1.3
Reddit Enhancer 0.16.1
Roomy Bookmarks Toolbar redux 1.7.7.6
Save Screenshot 10.0.0
Simple Context Search 1.3.0
simple-modify-headers 1.8.1
Skip Redirect 2.3.6
SponsorBlock for YouTube - Skip Sponsorships 5.4.12
Sticky Ducky 1.7.2
Switch to audible tab 0.0.9
Tab Mix Plus 1.0.0-pre.16
Tabhunter 3.5.2
Top and Bottom scroll buttons 1.8.0
uBlock Origin 1.51.0 (Updated at same time)
Violentmonkey 2.15.0
Visual Tabs 0.90
Windowed - floating Youtube/every website 31

**Comment by Mystqr4** [comment]
Tested and still crashing. Tested three times. 
Updated to Waterfox G5.1.10

**Comment by ACK-J** [comment]
This issue was solved in v2.0.0 https://github.com/ACK-J/Port_Authority/releases/tag/2.0.0 after fixing a memory leak
